# Generated by Django 5.1.6 on 2025-03-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0005_alter_customuser_groups_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
